"""initial operational schema

Revision ID: 4fe332cb2c9d
Revises:
Create Date: 2026-09-04 15:43:09.412533
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4fe332cb2c9d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_plan_issues",
        sa.Column("dataset_id", sa.String(length=255), nullable=False),
        sa.Column("distribution_id", sa.String(length=255), nullable=False),
        sa.Column("principal_id", sa.String(length=64), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mode", sa.String(length=24), nullable=False),
        sa.Column("client", sa.String(length=32), nullable=True),
        sa.Column("slice_spec", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "mode in ('redirect','partial-read','subsetting-protocol')",
            name=op.f("ck_access_plan_issues_plan_mode_known"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_plan_issues")),
    )
    with op.batch_alter_table("access_plan_issues", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_access_plan_issues_dataset_id"), ["dataset_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_access_plan_issues_distribution_id"), ["distribution_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_access_plan_issues_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_access_plan_issues_issued_at"), ["issued_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_access_plan_issues_principal_id"), ["principal_id"], unique=False
        )

    op.create_table(
        "allowlist_entries",
        sa.Column("dataset_id", sa.String(length=255), nullable=False),
        sa.Column("principal_id", sa.String(length=64), nullable=True),
        sa.Column("principal_email", sa.String(length=320), nullable=True),
        sa.Column("granted_by", sa.String(length=64), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "principal_id is not null or principal_email is not null",
            name=op.f("ck_allowlist_entries_principal_identified"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_allowlist_entries")),
        sa.UniqueConstraint("dataset_id", "principal_id", name="dataset_principal"),
    )
    with op.batch_alter_table("allowlist_entries", schema=None) as batch_op:
        batch_op.create_index("ix_allowlist_active", ["dataset_id", "revoked_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_allowlist_entries_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_allowlist_entries_dataset_id"), ["dataset_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_allowlist_entries_principal_email"), ["principal_email"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_allowlist_entries_principal_id"), ["principal_id"], unique=False
        )

    op.create_table(
        "authorization_events",
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("principal_id", sa.String(length=64), nullable=True),
        sa.Column("principal_kind", sa.String(length=16), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("resource_kind", sa.String(length=32), nullable=False),
        sa.Column("resource_id", sa.String(length=255), nullable=True),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=True),
        sa.Column("masked_as", sa.String(length=16), nullable=True),
        sa.Column("client", sa.String(length=32), nullable=True),
        sa.Column("tool_name", sa.String(length=64), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "outcome in ('granted','refused')", name=op.f("ck_authorization_events_outcome_known")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_authorization_events")),
    )
    with op.batch_alter_table("authorization_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_auth_principal_time", ["principal_id", "occurred_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_authorization_events_action"), ["action"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_authorization_events_occurred_at"), ["occurred_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_authorization_events_outcome"), ["outcome"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_authorization_events_principal_id"), ["principal_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_authorization_events_resource_id"), ["resource_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_authorization_events_tool_name"), ["tool_name"], unique=False
        )

    op.create_table(
        "distribution_health",
        sa.Column("distribution_id", sa.String(length=255), nullable=False),
        sa.Column("dataset_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("last_probed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_probe_due", sa.DateTime(timezone=True), nullable=True),
        sa.Column("probe_cadence_s", sa.Integer(), nullable=False),
        sa.Column("excluded_from_plans", sa.Boolean(), nullable=False),
        sa.Column("custodian_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("distribution_id", name=op.f("pk_distribution_health")),
    )
    with op.batch_alter_table("distribution_health", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_distribution_health_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_distribution_health_dataset_id"), ["dataset_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_distribution_health_excluded_from_plans"),
            ["excluded_from_plans"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_distribution_health_last_probed_at"), ["last_probed_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_distribution_health_next_probe_due"), ["next_probe_due"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_distribution_health_status"), ["status"], unique=False)

    op.create_table(
        "distribution_revisions",
        sa.Column("distribution_id", sa.String(length=255), nullable=False),
        sa.Column("dataset_id", sa.String(length=255), nullable=False),
        sa.Column("field", sa.String(length=64), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("automated", sa.Boolean(), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "source in ('probe','harvest','steward','report','migration')",
            name=op.f("ck_distribution_revisions_revision_source_known"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_distribution_revisions")),
    )
    with op.batch_alter_table("distribution_revisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_distribution_revisions_changed_at"), ["changed_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_distribution_revisions_dataset_id"), ["dataset_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_distribution_revisions_distribution_id"),
            ["distribution_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_revision_dist_time", ["distribution_id", "changed_at"], unique=False
        )

    op.create_table(
        "harvest_runs",
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("adapter", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("records_seen", sa.Integer(), nullable=False),
        sa.Column("records_accepted", sa.Integer(), nullable=False),
        sa.Column("records_rejected", sa.Integer(), nullable=False),
        sa.Column("records_updated", sa.Integer(), nullable=False),
        sa.Column("records_unchanged", sa.Integer(), nullable=False),
        sa.Column("records_flagged", sa.Integer(), nullable=False),
        sa.Column("errors", sa.Integer(), nullable=False),
        sa.Column("error_detail", sa.JSON(), nullable=False),
        sa.Column("checkpoint", sa.JSON(), nullable=True),
        sa.Column("limit_applied", sa.Integer(), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "state in ('running','succeeded','failed','cancelled')",
            name=op.f("ck_harvest_runs_run_state_known"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_harvest_runs")),
    )
    with op.batch_alter_table("harvest_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_harvest_runs_source_id"), ["source_id"], unique=False)
        batch_op.create_index(
            "ix_harvest_runs_source_started", ["source_id", "started_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_harvest_runs_started_at"), ["started_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_harvest_runs_state"), ["state"], unique=False)

    op.create_table(
        "probe_results",
        sa.Column("distribution_id", sa.String(length=255), nullable=False),
        sa.Column("dataset_id", sa.String(length=255), nullable=False),
        sa.Column("probed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("method", sa.String(length=8), nullable=False),
        sa.Column("redirect_target", sa.String(length=2000), nullable=True),
        sa.Column("redirect_permanent", sa.Boolean(), nullable=False),
        sa.Column("content_length", sa.Integer(), nullable=True),
        sa.Column("supports_range", sa.Boolean(), nullable=True),
        sa.Column("cors_enabled", sa.Boolean(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "status in ('verified','degraded','unreachable','redirected')",
            name=op.f("ck_probe_results_probe_status_known"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_probe_results")),
    )
    with op.batch_alter_table("probe_results", schema=None) as batch_op:
        batch_op.create_index("ix_probe_dist_time", ["distribution_id", "probed_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_probe_results_dataset_id"), ["dataset_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_probe_results_distribution_id"), ["distribution_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_probe_results_probed_at"), ["probed_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_probe_results_status"), ["status"], unique=False)

    op.create_table(
        "projector_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("last_commit_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pending_count", sa.Integer(), nullable=False),
        sa.Column("last_full_reindex_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.CheckConstraint("id = 1", name=op.f("ck_projector_state_singleton")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projector_state")),
    )
    op.create_table(
        "rate_limit_buckets",
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("key", "window_start", name=op.f("pk_rate_limit_buckets")),
    )
    op.create_table(
        "submissions",
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("originator", sa.String(length=300), nullable=True),
        sa.Column("data_domain", sa.String(length=16), nullable=True),
        sa.Column("license_text", sa.String(length=300), nullable=False),
        sa.Column("submitter_contact", sa.String(length=320), nullable=True),
        sa.Column("access_urls", sa.JSON(), nullable=False),
        sa.Column("format_hint", sa.String(length=120), nullable=True),
        sa.Column("approximate_size", sa.String(length=64), nullable=True),
        sa.Column("update_cadence", sa.String(length=64), nullable=True),
        sa.Column("documentation_urls", sa.JSON(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("triaged_by", sa.String(length=64), nullable=True),
        sa.Column("triaged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "state in ('received','triaged','accepted','declined','duplicate')",
            name=op.f("ck_submissions_submission_state_known"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_submissions")),
    )
    with op.batch_alter_table("submissions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_submissions_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_submissions_data_domain"), ["data_domain"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_submissions_ip_hash"), ["ip_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_submissions_state"), ["state"], unique=False)

    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_agent", sa.Boolean(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("role in ('user','steward','admin')", name=op.f("ck_users_role_known")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_role"), ["role"], unique=False)

    op.create_table(
        "api_tokens",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("prefix", sa.String(length=16), nullable=False),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_api_tokens_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_tokens")),
    )
    with op.batch_alter_table("api_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_tokens_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_api_tokens_prefix"), ["prefix"], unique=False)
        batch_op.create_index(batch_op.f("ix_api_tokens_token_hash"), ["token_hash"], unique=True)
        batch_op.create_index(batch_op.f("ix_api_tokens_user_id"), ["user_id"], unique=False)

    op.create_table(
        "custodianships",
        sa.Column("dataset_id", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=True),
        sa.Column("contact_email", sa.String(length=320), nullable=True),
        sa.Column("organisation", sa.String(length=200), nullable=True),
        sa.Column("may_delegate", sa.Boolean(), nullable=False),
        sa.Column("delegated_by", sa.String(length=64), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_custodianships_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_custodianships")),
        sa.UniqueConstraint("dataset_id", "user_id", name="dataset_custodian"),
    )
    with op.batch_alter_table("custodianships", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_custodianships_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_custodianships_dataset_id"), ["dataset_id"], unique=False
        )

    op.create_table(
        "hosted_copy_owners",
        sa.Column("distribution_id", sa.String(length=255), nullable=False),
        sa.Column("dataset_id", sa.String(length=255), nullable=False),
        sa.Column("owner_user_id", sa.String(length=32), nullable=True),
        sa.Column("owner_contact", sa.String(length=320), nullable=False),
        sa.Column("hosting_reason", sa.String(length=32), nullable=False),
        sa.Column("refresh_cadence", sa.String(length=64), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_refresh_due", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "hosting_reason in ('format','fragile-source','charges-user','etl-output')",
            name=op.f("ck_hosted_copy_owners_hosting_reason_known"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_hosted_copy_owners_owner_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hosted_copy_owners")),
    )
    with op.batch_alter_table("hosted_copy_owners", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_hosted_copy_owners_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_hosted_copy_owners_dataset_id"), ["dataset_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_hosted_copy_owners_distribution_id"), ["distribution_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_hosted_copy_owners_next_refresh_due"), ["next_refresh_due"], unique=False
        )

    op.create_table(
        "identities",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_identities_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identities")),
        sa.UniqueConstraint("provider", "subject", name="provider_subject"),
    )
    with op.batch_alter_table("identities", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_identities_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_identities_provider"), ["provider"], unique=False)
        batch_op.create_index(batch_op.f("ix_identities_subject"), ["subject"], unique=False)
        batch_op.create_index(batch_op.f("ix_identities_user_id"), ["user_id"], unique=False)

    op.create_table(
        "issue_reports",
        sa.Column("dataset_id", sa.String(length=255), nullable=False),
        sa.Column("target_kind", sa.String(length=16), nullable=False),
        sa.Column("target_id", sa.String(length=255), nullable=True),
        sa.Column("issue_type", sa.String(length=32), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("reporter_user_id", sa.String(length=32), nullable=True),
        sa.Column("reporter_contact", sa.String(length=320), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("resolved_by", sa.String(length=64), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duplicate_of", sa.String(length=32), nullable=True),
        sa.Column("forwarded_to_custodian_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "issue_type in ('incorrect-metadata','broken-link','license-question','wrong-classification','duplicate-record','other')",
            name=op.f("ck_issue_reports_issue_type_known"),
        ),
        sa.CheckConstraint(
            "state in ('open','triaged','resolved','rejected')",
            name=op.f("ck_issue_reports_report_state_known"),
        ),
        sa.CheckConstraint(
            "target_kind in ('dataset','field','distribution')",
            name=op.f("ck_issue_reports_target_kind_known"),
        ),
        sa.ForeignKeyConstraint(
            ["duplicate_of"],
            ["issue_reports.id"],
            name=op.f("fk_issue_reports_duplicate_of_issue_reports"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reporter_user_id"],
            ["users.id"],
            name=op.f("fk_issue_reports_reporter_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_issue_reports")),
    )
    with op.batch_alter_table("issue_reports", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_issue_reports_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_issue_reports_dataset_id"), ["dataset_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_issue_reports_ip_hash"), ["ip_hash"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_issue_reports_issue_type"), ["issue_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_issue_reports_state"), ["state"], unique=False)
        batch_op.create_index(batch_op.f("ix_issue_reports_target_id"), ["target_id"], unique=False)
        batch_op.create_index(
            "ix_reports_target", ["dataset_id", "target_id", "state"], unique=False
        )

    op.create_table(
        "raw_records",
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("source_record_id", sa.String(length=500), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("source_url", sa.String(length=2000), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["harvest_runs.id"],
            name=op.f("fk_raw_records_run_id_harvest_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_records")),
        sa.UniqueConstraint("source_id", "source_record_id", name="source_record"),
    )
    with op.batch_alter_table("raw_records", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_raw_records_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_raw_records_payload_hash"), ["payload_hash"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_raw_records_source_id"), ["source_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_raw_records_source_record_id"), ["source_record_id"], unique=False
        )

    op.create_table(
        "sessions",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sessions_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_sessions_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "relevance_decisions",
        sa.Column("raw_record_id", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted", sa.Boolean(), nullable=False),
        sa.Column("stage", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("matched_terms", sa.JSON(), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=True),
        sa.Column("prompt_version", sa.String(length=32), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "stage in ('keyword','vocabulary','llm')",
            name=op.f("ck_relevance_decisions_stage_known"),
        ),
        sa.ForeignKeyConstraint(
            ["raw_record_id"],
            ["raw_records.id"],
            name=op.f("fk_relevance_decisions_raw_record_id_raw_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_relevance_decisions")),
    )
    with op.batch_alter_table("relevance_decisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_relevance_decisions_accepted"), ["accepted"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_relevance_decisions_decided_at"), ["decided_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_relevance_decisions_raw_record_id"), ["raw_record_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_relevance_decisions_source_id"), ["source_id"], unique=False
        )

    op.create_table(
        "review_queue",
        sa.Column("dataset_id", sa.String(length=255), nullable=False),
        sa.Column("raw_record_id", sa.String(length=32), nullable=True),
        sa.Column("source_id", sa.String(length=64), nullable=True),
        sa.Column("data_domain", sa.String(length=16), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("completeness_level", sa.Integer(), nullable=False),
        sa.Column("inbound_link_count", sa.Integer(), nullable=False),
        sa.Column("validation_conforms", sa.Boolean(), nullable=False),
        sa.Column("violations", sa.JSON(), nullable=False),
        sa.Column("assigned_to", sa.String(length=32), nullable=True),
        sa.Column("reviewed_by", sa.String(length=64), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("steward_notes", sa.Text(), nullable=True),
        sa.Column("confirmed_fields", sa.JSON(), nullable=False),
        sa.Column("conflict_detail", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "state in ('draft','in-review','confirmed','flagged')",
            name=op.f("ck_review_queue_review_state_known"),
        ),
        sa.CheckConstraint(
            "completeness_level between 1 and 3", name=op.f("ck_review_queue_level_in_range")
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["users.id"],
            name=op.f("fk_review_queue_assigned_to_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["raw_record_id"],
            ["raw_records.id"],
            name=op.f("fk_review_queue_raw_record_id_raw_records"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_queue")),
    )
    with op.batch_alter_table("review_queue", schema=None) as batch_op:
        batch_op.create_index(
            "ix_review_priority", ["state", "data_domain", "inbound_link_count"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_review_queue_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_review_queue_data_domain"), ["data_domain"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_review_queue_dataset_id"), ["dataset_id"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_review_queue_inbound_link_count"), ["inbound_link_count"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_review_queue_source_id"), ["source_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_review_queue_state"), ["state"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("review_queue", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_review_queue_state"))
        batch_op.drop_index(batch_op.f("ix_review_queue_source_id"))
        batch_op.drop_index(batch_op.f("ix_review_queue_inbound_link_count"))
        batch_op.drop_index(batch_op.f("ix_review_queue_dataset_id"))
        batch_op.drop_index(batch_op.f("ix_review_queue_data_domain"))
        batch_op.drop_index(batch_op.f("ix_review_queue_created_at"))
        batch_op.drop_index("ix_review_priority")

    op.drop_table("review_queue")
    with op.batch_alter_table("relevance_decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_relevance_decisions_source_id"))
        batch_op.drop_index(batch_op.f("ix_relevance_decisions_raw_record_id"))
        batch_op.drop_index(batch_op.f("ix_relevance_decisions_decided_at"))
        batch_op.drop_index(batch_op.f("ix_relevance_decisions_accepted"))

    op.drop_table("relevance_decisions")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_sessions_expires_at"))
        batch_op.drop_index(batch_op.f("ix_sessions_created_at"))

    op.drop_table("sessions")
    with op.batch_alter_table("raw_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_raw_records_source_record_id"))
        batch_op.drop_index(batch_op.f("ix_raw_records_source_id"))
        batch_op.drop_index(batch_op.f("ix_raw_records_payload_hash"))
        batch_op.drop_index(batch_op.f("ix_raw_records_created_at"))

    op.drop_table("raw_records")
    with op.batch_alter_table("issue_reports", schema=None) as batch_op:
        batch_op.drop_index("ix_reports_target")
        batch_op.drop_index(batch_op.f("ix_issue_reports_target_id"))
        batch_op.drop_index(batch_op.f("ix_issue_reports_state"))
        batch_op.drop_index(batch_op.f("ix_issue_reports_issue_type"))
        batch_op.drop_index(batch_op.f("ix_issue_reports_ip_hash"))
        batch_op.drop_index(batch_op.f("ix_issue_reports_dataset_id"))
        batch_op.drop_index(batch_op.f("ix_issue_reports_created_at"))

    op.drop_table("issue_reports")
    with op.batch_alter_table("identities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_identities_user_id"))
        batch_op.drop_index(batch_op.f("ix_identities_subject"))
        batch_op.drop_index(batch_op.f("ix_identities_provider"))
        batch_op.drop_index(batch_op.f("ix_identities_created_at"))

    op.drop_table("identities")
    with op.batch_alter_table("hosted_copy_owners", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_hosted_copy_owners_next_refresh_due"))
        batch_op.drop_index(batch_op.f("ix_hosted_copy_owners_distribution_id"))
        batch_op.drop_index(batch_op.f("ix_hosted_copy_owners_dataset_id"))
        batch_op.drop_index(batch_op.f("ix_hosted_copy_owners_created_at"))

    op.drop_table("hosted_copy_owners")
    with op.batch_alter_table("custodianships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_custodianships_dataset_id"))
        batch_op.drop_index(batch_op.f("ix_custodianships_created_at"))

    op.drop_table("custodianships")
    with op.batch_alter_table("api_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_tokens_user_id"))
        batch_op.drop_index(batch_op.f("ix_api_tokens_token_hash"))
        batch_op.drop_index(batch_op.f("ix_api_tokens_prefix"))
        batch_op.drop_index(batch_op.f("ix_api_tokens_created_at"))

    op.drop_table("api_tokens")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_role"))
        batch_op.drop_index(batch_op.f("ix_users_email"))
        batch_op.drop_index(batch_op.f("ix_users_created_at"))

    op.drop_table("users")
    with op.batch_alter_table("submissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_submissions_state"))
        batch_op.drop_index(batch_op.f("ix_submissions_ip_hash"))
        batch_op.drop_index(batch_op.f("ix_submissions_data_domain"))
        batch_op.drop_index(batch_op.f("ix_submissions_created_at"))

    op.drop_table("submissions")
    op.drop_table("rate_limit_buckets")
    op.drop_table("projector_state")
    with op.batch_alter_table("probe_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_probe_results_status"))
        batch_op.drop_index(batch_op.f("ix_probe_results_probed_at"))
        batch_op.drop_index(batch_op.f("ix_probe_results_distribution_id"))
        batch_op.drop_index(batch_op.f("ix_probe_results_dataset_id"))
        batch_op.drop_index("ix_probe_dist_time")

    op.drop_table("probe_results")
    with op.batch_alter_table("harvest_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_harvest_runs_state"))
        batch_op.drop_index(batch_op.f("ix_harvest_runs_started_at"))
        batch_op.drop_index("ix_harvest_runs_source_started")
        batch_op.drop_index(batch_op.f("ix_harvest_runs_source_id"))

    op.drop_table("harvest_runs")
    with op.batch_alter_table("distribution_revisions", schema=None) as batch_op:
        batch_op.drop_index("ix_revision_dist_time")
        batch_op.drop_index(batch_op.f("ix_distribution_revisions_distribution_id"))
        batch_op.drop_index(batch_op.f("ix_distribution_revisions_dataset_id"))
        batch_op.drop_index(batch_op.f("ix_distribution_revisions_changed_at"))

    op.drop_table("distribution_revisions")
    with op.batch_alter_table("distribution_health", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_distribution_health_status"))
        batch_op.drop_index(batch_op.f("ix_distribution_health_next_probe_due"))
        batch_op.drop_index(batch_op.f("ix_distribution_health_last_probed_at"))
        batch_op.drop_index(batch_op.f("ix_distribution_health_excluded_from_plans"))
        batch_op.drop_index(batch_op.f("ix_distribution_health_dataset_id"))
        batch_op.drop_index(batch_op.f("ix_distribution_health_created_at"))

    op.drop_table("distribution_health")
    with op.batch_alter_table("authorization_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_authorization_events_tool_name"))
        batch_op.drop_index(batch_op.f("ix_authorization_events_resource_id"))
        batch_op.drop_index(batch_op.f("ix_authorization_events_principal_id"))
        batch_op.drop_index(batch_op.f("ix_authorization_events_outcome"))
        batch_op.drop_index(batch_op.f("ix_authorization_events_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_authorization_events_action"))
        batch_op.drop_index("ix_auth_principal_time")

    op.drop_table("authorization_events")
    with op.batch_alter_table("allowlist_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_allowlist_entries_principal_id"))
        batch_op.drop_index(batch_op.f("ix_allowlist_entries_principal_email"))
        batch_op.drop_index(batch_op.f("ix_allowlist_entries_dataset_id"))
        batch_op.drop_index(batch_op.f("ix_allowlist_entries_created_at"))
        batch_op.drop_index("ix_allowlist_active")

    op.drop_table("allowlist_entries")
    with op.batch_alter_table("access_plan_issues", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_access_plan_issues_principal_id"))
        batch_op.drop_index(batch_op.f("ix_access_plan_issues_issued_at"))
        batch_op.drop_index(batch_op.f("ix_access_plan_issues_expires_at"))
        batch_op.drop_index(batch_op.f("ix_access_plan_issues_distribution_id"))
        batch_op.drop_index(batch_op.f("ix_access_plan_issues_dataset_id"))

    op.drop_table("access_plan_issues")
    # ### end Alembic commands ###
